<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-7S7LCUO" failures="2" tests="6" name="parallel.ParallelRun" time="40.110" errors="0" timestamp="2024-04-03T14:43:17 IST" skipped="0">
  <testcase classname="parallel.ParallelRun" name="runScenario" time="8.065"/>
  <testcase classname="parallel.ParallelRun" name="runScenario" time="5.465"/>
  <testcase classname="parallel.ParallelRun" name="runScenario" time="6.526">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at parallel.Login.user_should_be_redirected_to_the_dashboard(Login.java:39)
at ✽.user should be redirected to the dashboard "2Test Automation Practice: Working with Secure Page"(file:///C:/Users/Hustler/eclipse-workspace/CucumberPOM/src/test/resources/parallel/Login.feature:21)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="parallel.ParallelRun" name="runScenario" time="6.244"/>
  <testcase classname="parallel.ParallelRun" name="runScenario" time="8.119"/>
  <testcase classname="parallel.ParallelRun" name="runScenario" time="5.691">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
at org.junit.Assert.fail(Assert.java:87)
at org.junit.Assert.assertTrue(Assert.java:42)
at org.junit.Assert.assertTrue(Assert.java:53)
at parallel.Login.user_should_be_redirected_to_the_dashboard(Login.java:39)
at ✽.user should be redirected to the dashboard "1Test Automation Practice: Working with Login form"(file:///C:/Users/Hustler/eclipse-workspace/CucumberPOM/src/test/resources/parallel/Login.feature:27)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- parallel.ParallelRun -->
